version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      # We inject the connection string here (Environment Variable)
      - MONGO_URI=${MONGO_URI}
      - PORT=5000

  client:
    build: ./client
    ports:
      - "8080:80" # Map local port 8080 to container port 80
    depends_on:
      - server